<link rel="stylesheet" href="{{assets_url('css/bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{assets_url('css/ionicons.min.css')}}">
<link rel="stylesheet" href="{{assets_url('css/style.css')}}">
<link rel="stylesheet" href="{{assets_url('css/slick.css')}}">
<link rel="stylesheet" href="{{assets_url('css/slick-theme.css')}}">
<link rel="stylesheet" href="{{assets_url('css/font-face.css')}}">
<link rel="stylesheet" href="{{assets_url('fonts/fonts.css')}}">
<link rel="stylesheet" href="{{assets_url('css/swiper-bundle.min.css')}}">
<link rel="stylesheet" href="{{assets_url('css/aos.css')}}">